DROP DATABASE IF EXISTS bus_room_schedule;
CREATE DATABASE bus_room_schedule CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bus_room_schedule;

CREATE TABLE IF NOT EXISTS admins (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS buses (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    bus_number VARCHAR(50) NOT NULL,
    total_seats INT UNSIGNED NOT NULL DEFAULT 49,
    origin VARCHAR(150) NULL,
    destination VARCHAR(150) NULL,
    bus_type VARCHAR(50) NOT NULL DEFAULT 'Normal',
    description TEXT NULL,
    image_url TEXT NULL,
    start_time TIME NULL,
    end_time TIME NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS seats (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    bus_id INT UNSIGNED NOT NULL,
    seat_number VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_seats_bus FOREIGN KEY (bus_id) REFERENCES buses(id) ON DELETE CASCADE,
    CONSTRAINT uq_bus_seat UNIQUE (bus_id, seat_number)
);

CREATE TABLE IF NOT EXISTS bookings (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    bus_id INT UNSIGNED NOT NULL,
    travel_date DATE NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    pickup_point VARCHAR(150) NOT NULL,
    drop_location VARCHAR(150) NOT NULL,
    status ENUM('pending', 'booked', 'available') NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bookings_bus FOREIGN KEY (bus_id) REFERENCES buses(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS booking_seats (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    booking_id INT UNSIGNED NOT NULL,
    seat_id INT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_booking_seats_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_seats_seat FOREIGN KEY (seat_id) REFERENCES seats(id) ON DELETE CASCADE,
    CONSTRAINT uq_booking_seat UNIQUE (booking_id, seat_id)
);

CREATE TABLE IF NOT EXISTS seat_status_overrides (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    bus_id INT UNSIGNED NOT NULL,
    seat_id INT UNSIGNED NOT NULL,
    travel_date DATE NOT NULL,
    status ENUM('available', 'pending', 'booked') NOT NULL DEFAULT 'available',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_overrides_bus FOREIGN KEY (bus_id) REFERENCES buses(id) ON DELETE CASCADE,
    CONSTRAINT fk_overrides_seat FOREIGN KEY (seat_id) REFERENCES seats(id) ON DELETE CASCADE,
    CONSTRAINT uq_override UNIQUE (bus_id, seat_id, travel_date)
);

CREATE TABLE IF NOT EXISTS bus_stops (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    bus_id INT UNSIGNED NOT NULL,
    stop_name VARCHAR(150) NOT NULL,
    stop_offset_minutes INT UNSIGNED NOT NULL DEFAULT 0,
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bus_stops_bus FOREIGN KEY (bus_id) REFERENCES buses(id) ON DELETE CASCADE,
    CONSTRAINT uq_bus_stop UNIQUE (bus_id, stop_name)
);

INSERT INTO admins (username, password_hash)
VALUES ('admin', '$2y$10$2PKTg2IqySDovY3JtbiPIe1QHmHE.KK8ZnNii7wNQSqEBuCDEkrnS');

INSERT INTO buses (name, bus_number, total_seats, bus_type, is_active)
VALUES
('Bus 1', 'NB-1001', 49, 'Normal', 1),
('Bus 2', 'NB-1002', 49, 'Normal', 1);

INSERT INTO seats (bus_id, seat_number)
SELECT b.id, seat_numbers.seat_number
FROM buses b
JOIN (
    SELECT '01' AS seat_number UNION ALL SELECT '02' UNION ALL SELECT '03' UNION ALL SELECT '04'
    UNION ALL SELECT '05' UNION ALL SELECT '06' UNION ALL SELECT '07' UNION ALL SELECT '08'
    UNION ALL SELECT '09' UNION ALL SELECT '10' UNION ALL SELECT '11' UNION ALL SELECT '12'
    UNION ALL SELECT '13' UNION ALL SELECT '14' UNION ALL SELECT '15' UNION ALL SELECT '16'
    UNION ALL SELECT '17' UNION ALL SELECT '18' UNION ALL SELECT '19' UNION ALL SELECT '20'
    UNION ALL SELECT '21' UNION ALL SELECT '22' UNION ALL SELECT '23' UNION ALL SELECT '24'
    UNION ALL SELECT '25' UNION ALL SELECT '26' UNION ALL SELECT '27' UNION ALL SELECT '28'
    UNION ALL SELECT '29' UNION ALL SELECT '30' UNION ALL SELECT '31' UNION ALL SELECT '32'
    UNION ALL SELECT '33' UNION ALL SELECT '34' UNION ALL SELECT '35' UNION ALL SELECT '36'
    UNION ALL SELECT '37' UNION ALL SELECT '38' UNION ALL SELECT '39' UNION ALL SELECT '40'
    UNION ALL SELECT '41' UNION ALL SELECT '42' UNION ALL SELECT '43' UNION ALL SELECT '44'
    UNION ALL SELECT '45' UNION ALL SELECT '46' UNION ALL SELECT '47' UNION ALL SELECT '48'
    UNION ALL SELECT '49'
) AS seat_numbers
WHERE b.bus_number = 'NB-1001';

INSERT INTO seats (bus_id, seat_number)
SELECT b.id, seat_numbers.seat_number
FROM buses b
JOIN (
    SELECT '01' AS seat_number UNION ALL SELECT '02' UNION ALL SELECT '03' UNION ALL SELECT '04'
    UNION ALL SELECT '05' UNION ALL SELECT '06' UNION ALL SELECT '07' UNION ALL SELECT '08'
    UNION ALL SELECT '09' UNION ALL SELECT '10' UNION ALL SELECT '11' UNION ALL SELECT '12'
    UNION ALL SELECT '13' UNION ALL SELECT '14' UNION ALL SELECT '15' UNION ALL SELECT '16'
    UNION ALL SELECT '17' UNION ALL SELECT '18' UNION ALL SELECT '19' UNION ALL SELECT '20'
    UNION ALL SELECT '21' UNION ALL SELECT '22' UNION ALL SELECT '23' UNION ALL SELECT '24'
    UNION ALL SELECT '25' UNION ALL SELECT '26' UNION ALL SELECT '27' UNION ALL SELECT '28'
    UNION ALL SELECT '29' UNION ALL SELECT '30' UNION ALL SELECT '31' UNION ALL SELECT '32'
    UNION ALL SELECT '33' UNION ALL SELECT '34' UNION ALL SELECT '35' UNION ALL SELECT '36'
    UNION ALL SELECT '37' UNION ALL SELECT '38' UNION ALL SELECT '39' UNION ALL SELECT '40'
    UNION ALL SELECT '41' UNION ALL SELECT '42' UNION ALL SELECT '43' UNION ALL SELECT '44'
    UNION ALL SELECT '45' UNION ALL SELECT '46' UNION ALL SELECT '47' UNION ALL SELECT '48'
    UNION ALL SELECT '49'
) AS seat_numbers
WHERE b.bus_number = 'NB-1002';

-- Default admin login:
-- username: admin
-- password: admin123
